### ISSUE TITLE
Bug: `objectTypeToEZ` missing Map case, causing "MAP" to leak in error messages (regression from #904)

### ISSUE THREAD

**Issue by SchoolyB** [SchoolyB/EZ#945]
## Description

PR #904 fixed internal type names leaking by adding `KeyType` and `ValueType` fields to the Map struct. However, the `objectTypeToEZ` function in the interpreter was not updated to handle maps, causing `MAP` to still leak in return type mismatch errors.

## Example

```ez
module utils

import @db, @maps

do get_map() -> map[string:string] {
    temp m map[string:string] = {}
    maps.set(m, "key", "value")
    return m
}
```

**Error:**
```
error[E5012]: return type mismatch: expected map[string:string], got MAP
  --> file.ez:8:12
   |
 8 |     return m
   |            ^ error occurred here
```

The expected type shows correctly as `map[string:string]`, but the actual type shows as `MAP` (the internal Go type name).

## Root Cause

In `pkg/interpreter/evaluator.go`, the `objectTypeToEZ` function (lines 3188-3231) handles various types but is **missing a case for `*Map`**:

```go
func objectTypeToEZ(obj Object) string {
    switch v := obj.(type) {
    case *Integer:
        return v.GetDeclaredType()
    case *Array:
        if v.ElementType != "" {
            return "[" + v.ElementType + "]"
        }
        return "array"
    // ... other cases ...
    // NO CASE FOR *Map!
    default:
        return string(obj.Type())  // Falls through here, returns "MAP"
    }
}
```

## Suggested Fix

Add a case for `*Map` in `objectTypeToEZ`:

```go
case *Map:
    if v.KeyType != "" && v.ValueType != "" {
        return "map[" + v.KeyType + ":" + v.ValueType + "]"
    }
    return "map"
```

## Related

- Original issue: #900
- PR that partially fixed it: #904 (added `KeyType`/`ValueType` to Map struct but missed `objectTypeToEZ`)

## Related Code

- `pkg/interpreter/evaluator.go` lines 3188-3231 (`objectTypeToEZ` function)
- `pkg/object/object.go` lines 422-428 (Map struct with KeyType/ValueType fields)
