### ISSUE TITLE
bug: instance dispatch does not bind the receiver for an imported struct type

### ISSUE THREAD

**Issue by SchoolyB** [SchoolyB/EZ#2492]
Calling a struct function through an instance (`m.describe()`) fails when the struct is declared in an imported module. The function resolves, but the receiver is never prepended, so the call is rejected for having too few arguments.

## Reproduction

`msg.gray`

```grayscale
const Msg struct {
    id int

    do describe(m Msg) -> string {
        return "msg-${m.id}"
    }
}
```

`main.gray`

```grayscale
import "./msg.gray"

do main() {
    mut m msg.Msg = msg.Msg{id: 1}
    println(m.describe())
}
```

## Expected

Per STANDARD.md section 7.7 "Instance Dispatch", `m.describe()` rewrites to `Msg.describe(m)` and prints `msg-1`. That is what happens when `Msg` is declared in the same file.

## Actual

```
error[E5008]: function 'Msg.describe' expects 1 argument(s), got 0
  --> main.gray:5:23
   |
  5 |     println(m.describe())
   |                       ^
```

## Regression

Bisected to `4a3aec93` — `refactor(module-system): stop renaming identifiers at import merge`. The case compiled and ran correctly before that commit.

## Root cause

`grayc/src/typechecker/typechecker.c:4108-4118`:

```c
FuncSig *ssig = find_func(checker, sfn);   // resolved via checker_resolve_decl_into()
...
const char *p0_tn = ssig->decl->data.func_decl.params[0].type_name;
if (p0_tn) {
    if (strcmp(p0_tn, struct_name) == 0) {
        is_self_func = true;
    } else if (p0_tn[0] == '^' && strcmp(p0_tn + 1, struct_name) == 0) {
        is_self_func = true;
    }
}
```

`struct_name` comes from the symbol's type and is the mangled form; `p0_tn` is the parameter type as written inside the declaring module. Instrumenting the comparison:

```
cross-module:  struct_name=msg_Msg  p0_tn=Msg   -> strcmp fails -> E5008
same-file:     struct_name=Msg      p0_tn=Msg   -> matches -> works
```

The function lookup immediately above already goes through `checker_resolve_decl_into()`, which is why `Msg.describe` is found at all. This self-parameter comparison is a raw `strcmp` on unresolved names — one of the sites the symbol-table refactor did not convert. The same comparison repeats at line ~4172 for the auto-deref decision and needs the same treatment.

Note that `typechecker_same_struct_type()` (line 436) is currently `(void)checker; return a == b || strcmp(a, b) == 0;`, so it cannot be used as-is — the module-alias awareness described in the comment above `typechecker_same_array_element` is gone.

## Scope

Writing the type unqualified does not help; the mangling is on the symbol's type, not the written name. Both of these fail identically:

```grayscale
import "./msg.gray"
mut m msg.Msg = ...        // m.describe() -> E5008
```

```grayscale
import and use "./msg.gray"
mut m Msg = ...            // m.describe() -> E5008
```

## Workaround

The fully-qualified form works:

```grayscale
println(msg.Msg.describe(m))   // msg-1
```

## Test coverage gap

`integration-tests/pass/multi-file/` has 66 cases, none of which declares a struct in one module and calls a struct function on an *instance* of it from another. `struct-namespaced-functions/` only uses the fully-qualified form; `struct-func-cross-module-enum/` uses instance dispatch but declares `Painter` locally and imports only the enum.

**Comment by SchoolyB** [comment]
fixed
