### ISSUE TITLE
bug: enum values in typed array literals rejected with 'expected T got T', and for_each iteration loses enum type for when/is dispatch

### ISSUE THREAD

**Issue by SchoolyB** [SchoolyB/EZ#1802]
## Description

The typechecker does not recognize enum values as their enum type in collection contexts. Scalar enum assignment and `when`/`is` dispatch work correctly, but the moment an enum value enters an array literal or a `for_each` loop variable, the type information is lost or mismatched — producing errors where both sides of the comparison are the same type.

## Reproduction

**1. Typed array literal (integer enum)**
```ez
const Op enum {
    ADD
    SUB
    MUL
}

do main() {
    mut ops [Op] = {Op.ADD, Op.SUB, Op.MUL}
}
```
```
error[E3053]: type mismatch in array initializer; expected 'Op', got 'Op'
```

**2. for_each iteration element loses enum type for when/is**
```ez
do main() {
    mut ops [Op] = {Op.ADD, Op.SUB}  // already fails, but if it didn't:
    for_each i, op in ops {
        when op {
            is Op.ADD { println("add") }  // E3018: comparing 'Op' with 'Op'
            default {}
        }
    }
}
```
```
error[E3018]: type mismatch in 'when'; comparing 'Op' with 'Op'
```

## Expected Behavior

Enum values should be accepted in typed array literals and array element variables from `for_each` should retain their enum type for `when`/`is` dispatch.

## Notes

- Affects both integer enums and string enums (string enum array failure already reported in #1801)
- Scalar enum assignment and scalar `when`/`is` work correctly — this is isolated to collection contexts
- The error message is self-contradictory: `expected 'Op', got 'Op'` — both sides show the same type, indicating the typechecker is comparing two different internal representations of the same enum

**Comment by SchoolyB** [comment]
Fixed as part of #1801 — the tc_type_from_name() changes in the typechecker corrected array initializer element type resolution for integer enums as well.
