### ISSUE TITLE
bug: importing the same module twice in one file is accepted and corrupts the second binding

### ISSUE THREAD

**Issue by SchoolyB** [SchoolyB/EZ#2507]
A file that imports the same module twice should be rejected at compile time. This applies to standard library and user-defined modules alike, and to every syntactic form - the two imports need not be written the same way to be the same import. Today all of them are accepted, and the second one is left broken.

## Expected

An error on the duplicate import, naming the module. There is no code for this yet; `E6004` is the closest neighbour, and `E6005`, `E6006`, and `E6009` are free in the `imports` range.

Every one of these is the same module imported twice and must be rejected:

| Form | Verified result today |
|---|---|
| `import @math, @math` | accepted |
| `import @math` then `import @math` | accepted |
| `import and use @math, @math` | accepted |
| `import @math` then `import and use @math` | accepted |
| `import "./abc.gray", "./abc"` | accepted, `W2013` |
| `import "./abc"` then `import "./abc.gray"` | accepted, `W2013` |
| `import and use "./abc.gray"` then `import "./abc"` | accepted, `W2013` |
| `import ABC "./abc", "./abc.gray"` | accepted, binding broken |
| `import and use ABC "./abc"` then `import "./abc.gray"` | accepted, `W2015` |
| `import "./lib", other "./lib"` (directory) | accepted, binding broken |

Standard library imports cannot be aliased (`E6007`), so the aliased rows apply to user modules only.

## Actual - the plain forms report the surviving import as unused

`abc.gray`:

```grayscale
do f() -> int {
    return 1
}
```

`main.gray`:

```grayscale
import "./abc.gray", "./abc"

do main() {
    println(abc.f())
}
```

```
warning[W2013]: module 'abc' is already imported; duplicate import ignored
  --> main.gray:1:1
   |
  1 | import "./abc.gray", "./abc"
   | ^

warning[W1002]: module 'abc' is imported but never used; remove the import or use the module
  --> main.gray:1:1
   |
  1 | import "./abc.gray", "./abc"
   | ^
```

The program prints `1` correctly. The second import is discarded, but the discarded record is the one usage tracking consults, so the surviving import is never marked used and the compiler advises removing an import the program depends on. `import @math, @math` produces the same false `W1002`.

## Actual - the aliased forms leave the second name empty

`main.gray`:

```grayscale
import ABC "./abc", "./abc.gray"

do main() {
    println(ABC.f())
    println(abc.f())
}
```

```
warning[W2015]: file './abc.gray' was already imported as part of a directory import; use the 'ABC' namespace (e.g. ABC.abc()) instead
  --> main.gray:1:1
   |
  1 | import ABC "./abc", "./abc.gray"
   | ^

error[E4023]: module 'abc' has no function named 'f'
  --> main.gray:5:20
   |
  5 |     println(abc.f())
   |                    ^
```

Only the first name receives the module's symbols; the second is registered and never populated. Reversing the order moves the failure to the other name, so it is positional. Each import works on its own.

`W2015` is also wrong here on its own terms: `./abc.gray` is a plain file, there is no directory import anywhere in this project, and `ABC.abc()` suggests calling a function named after the file. The same warning appears for `import "./lib", other "./lib"`, where the target is a directory and the suggestion becomes `lib.lib()`.

## Not affected

Two different files each importing the same module once is a normal diamond dependency and must keep working. `main.gray` importing `./a` and `./b` while `b.gray` imports `./a` compiles clean with no warning today.

## Suggested labels

bug, module-system, error-messages

**Comment by SchoolyB** [comment]
fixed
