### ISSUE TITLE
bug: UBSan/ASan runtime test targets link an incomplete source list, breaking macOS CI

### ISSUE THREAD

**Issue by SchoolyB** [SchoolyB/EZ#2389]
## Description

The `test-ubsan` and `test-asan` Makefile targets hardcode the runtime source list for the runtime test binary, and that list is missing `src/runtime/atomic_builtin.c`. The link fails with an undefined `gray_atomic_load32` symbol, so the sanitizer runtime tests cannot build at all.

This is what currently breaks the macOS CI job. It is not macOS-specific — the same link fails on Linux too; that job just dies earlier in `test-unit` and never reaches `test-ubsan`.

## Expected behavior

`make test-ubsan` and `make test-asan` build and run the runtime test suite under the sanitizers.

## Actual behavior

```
=== UBSan Runtime Tests ===
Undefined symbols for architecture arm64:
  "_gray_atomic_load32", referenced from:
      _gray_array_set in array-6e6a9c.o
      _gray_array_push in array-6e6a9c.o
      _gray_map_set in map-a99f7b.o
      _gray_map_remove in map-a99f7b.o
      _gray_map_clear in map-a99f7b.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [test-ubsan] Error 1
make: *** [test-ubsan] Error 2
```

## Minimal reproduction

```sh
cd grayc
cc -fsanitize=undefined -Isrc -o /tmp/test_runtime_san \
   tests/test_runtime.c src/runtime/runtime.c src/runtime/array.c src/runtime/map.c -lm
```

## Root cause

`gray_atomic_load32` is defined in `grayc/src/runtime/atomic_builtin.c:70` and referenced from `grayc/src/runtime/array.c:45,55` and `grayc/src/runtime/map.c:210,258,279`.

The regular test target links it correctly via the object list:

```make
# grayc/Makefile:204
RT_TEST_DEPS = src/runtime/runtime.o src/runtime/array.o src/runtime/map.o $(ATOMIC_OBJ)
```

But the sanitizer targets duplicate the list by hand and omit it:

```make
# grayc/Makefile:316 (test-ubsan)
@$(CC) $(UBSAN_FLAGS) $(INCLUDES) -o tests/test_runtime_san$(EXE) \
    tests/test_runtime.c src/runtime/runtime.c src/runtime/array.c src/runtime/map.c $(LDFLAGS)

# grayc/Makefile:336 (test-asan) — same omission
```

The atomic call sites were introduced in 49d8eaa6 `security(runtime): use atomic ops for array/map iteration guards (#2302)`, which updated `RT_TEST_DEPS` but not the two hardcoded sanitizer command lines. The sanitizer targets have been unbuildable since that commit.

## Suggested fix

Adding `src/runtime/atomic_builtin.c` to both command lines links clean and the suite passes 38/38 under UBSan (verified locally on macOS arm64).

The durable fix is to stop duplicating the list — derive the sanitizer sources from `$(RT_TEST_DEPS:.o=.c)`, or introduce a shared `RT_TEST_SRCS` variable used by both the normal and sanitizer targets, so the two lists cannot drift apart again.

Both `test-ubsan` (line 316) and `test-asan` (line 336) need the change.

**Comment by SchoolyB** [comment]
fixed
